#!/bin/bash

RED='\033[0;31m'
YELLOW='\033[0;33m'
GREEN='\033[0;92m'
NC='\033[0m'

#!/bin/bash

# 定义要执行的命令
COMMAND='cd WCTOOL && chmod +x WC && ./WC && cd'

# 函数：检查别名是否已存在
alias_exists() {
    grep -Fxq "alias $1='$COMMAND'" ~/.bashrc
}

# 函数：添加别名到 ~/.bashrc
add_alias() {
    echo "alias $1='$COMMAND'" >> ~/.bashrc
    echo -e "${GREEN}快捷指令 '$1' 已成功创建${NC}"
}

# 函数：检查 ~/.bashrc 是否存在，如果不存在则创建
check_bashrc() {
    if [ ! -f ~/.bashrc ]; then
        touch ~/.bashrc
    fi
}

# 函数：提示用户输入别名名称
get_alias_name() {
    while true; do
        read -p "请输入您想要的快捷指令名称（例如 91）： " ALIAS_NAME
        # 检查输入是否为空
        if [ -z "$ALIAS_NAME" ]; then
            echo -e "${RED}快捷指令名称不能为空请重新输入${NC}"
        else
            break
        fi
    done
}

# 主逻辑
echo -e "${YELLOW}创建快捷指令${NC}"

# 检查 ~/.bashrc 是否存在，如果不存在则创建
check_bashrc

# 获取用户输入的别名名称
get_alias_name

# 检查别名是否已存在
if alias_exists "$ALIAS_NAME"; then
    echo -e "${RED}快捷指令 '$ALIAS_NAME' 已存在${NC}"
else
    # 添加别名到 ~/.bashrc
    add_alias "$ALIAS_NAME"  
    # 重新加载 .bashrc 文件
    source ~/.bashrc
    # 重新启动 bash 以使别名生效
    exec bash    
fi

echo -e "${GREEN}快捷指令创建完成${NC}"
